services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
  fos_user.doctrine_registry:
    alias: doctrine
  user_bundle.registration.form.type:
    class: UserBundle\Form\Type\RegistrationFormType
    tags:
      - { name: form.type, alias: user_registration }
  user_bundle.profile.form.type:
    class: UserBundle\Form\Type\ProfileFormType
    tags:
      - { name: form.type, alias: user_profile }
  fos_mail.custom_mailer:
    class: UserBundle\Mailer\CustomTwigSwiftMailer
    public: true
    arguments:
      - "@mailer"
      - "@router"
      - "@twig"
      - template:
          confirmation: "%fos_user.registration.confirmation.template%"
          resetting: "%fos_user.resetting.email.template%"
        from_email:
          confirmation: "%fos_user.registration.confirmation.from_email%"
          resetting: "%fos_user.resetting.email.from_email%"
